### ISSUE TITLE
Inline CSS

### ISSUE THREAD

**Issue by monochromer** [bem/bem-express#139]
Приветствую! Подскажите, как сделать, чтобы CSS, который собирается для каждой страницы, инлайнился в секцию head, а не сохранялся в отдельный файл?

**Comment by tadatuta** [comment]
@monochromer Вот так: https://github.com/bem/bem-express/compare/inline-css

**Comment by monochromer** [comment]
@tadatuta Спасибо!

**Comment by monochromer** [comment]
Посмотрел подробнее как работает эта методика. Получается, что сначала создается css-файл, потом считывается из файловой системы и инлайнится шаблонизатором. Можно ли как-то избежать процесс записи в файл? Ведь сборщик bem на каком-то этапе уже имеет строку со стилями и ее можно сразу передать шаблонизатору.
