### ISSUE TITLE
.DS_store break tests

### ISSUE THREAD

**Issue by Realetive** [bem/bem-express#141]
![2017-06-29 2 01 42](https://user-images.githubusercontent.com/2073959/27664203-ead57cf0-5c6e-11e7-9143-a3307d6465fe.png)

As a fast fix: `find . -name '.DS_Store' -type f -delete` before run tests.

**Comment by tadatuta** [comment]
Should be fixed in https://github.com/bemhint/bemhint-fs-naming/issues/4
